leftnav:
- identifier: 88d08e5d-65a1-7f90-f676-54834cda4e50
  name: Syllabus
  url: content/sections/syllabus
  weight: 10
- identifier: 0e970194-618e-a606-d850-fe9b02118400
  name: Calendar
  url: content/sections/calendar
  weight: 20
- identifier: 9de35c7e-5da7-cb90-0e93-d689bb4f6003
  name: Readings
  url: content/sections/readings
  weight: 30
- identifier: 71275da2-27cc-624e-d06f-7bd0fe95ec01
  name: Lecture Notes
  url: content/sections/lecture-notes/
  weight: 40
- identifier: ab19bbb3-c3b1-7a1a-e845-bc698eaf6b0f
  name: Study Materials
  url: content/sections/study-materials/
  weight: 50
- identifier: f03329c6-d683-2f08-7415-3a2759447339
  name: Related Resources
  url: content/sections/related-resources
  weight: 60
title: Left Nav
